### ISSUE TITLE
Update this thing

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/corefx-progress#2]
It's not really useful otherwise :)

/cc @terrajobst

**Comment by ellismg** [comment]
Can we just whip up some internal automation to do this nightly or something?

**Comment by terrajobst** [comment]
@akoeplinger Done!

@ellismg: we can now! I've made it such we can simply run `update.ps1` and it will generate everything, including the chart (which was manual before). Let's talk about this in person.

**Comment by akoeplinger** [comment]
@terrajobst I think something broke with the automation, I'm not seeing any updates for the last two week?

**Comment by ellismg** [comment]
There were some issues in the scripts which prevented me from running this daily and I haven't had a chance to get them fixed or bug Immo about it).  I will hold it's hand today and update it and then work on fixing the scripts so they can run daily.
