### ISSUE TITLE
Is WCF on the open source roadmap?

### ISSUE THREAD

**Issue by rmichela** [dotnet/corefx-progress#4]
I see a few System.ServiceModel dlls in src-full, but they don't seem to correlate to the WCF assemblies I normally use. Will WCF be opened? Particularly System.ServiceModel.* assemblies and System.Runtime.Serialization?

**Comment by akoeplinger** [comment]
System.ServiceModel is already open source at https://github.com/Microsoft/referencesource/tree/master/System.ServiceModel.

As far as I know, there are no plans to bring the server-side parts of WCF to .NET Core, only the client-side parts that let you interact with WCF services.

**Comment by rmichela** [comment]
Thanks for the quick response @akoeplinger. I guess that means no self-hosted WCF services running on linux for now. :disappointed:

**Comment by dotnetchris** [comment]
I'm really excited about CoreCLR getting the client bits for WCF, that's what matters most.

**Comment by MikePopoloski** [comment]
https://github.com/dotnet/wcf
